---
- name: Set Environment Variables for Flask App
  hosts: all
  become: true

  tasks:
    - name: Create environment variable file for Flask
      copy:
        content: |
          export FLASK_APP=app.py
          export FLASK_ENV=production
        dest: /etc/profile.d/flask_env.sh
        mode: '0644'
...