---
- name: Install Python and Flask
  hosts: app
  become: true

  tasks:
    - name: Install Python and Flask
      yum:
        name:
          - python3
          - python3-pip
        state: present
...