---
- name: Copy application files
  copy:
    src: flask-app.tar.gz
    dest: /home/centos/flask-app.tar.gz
  become: true

- name: Extract application
  unarchive:
    src: /home/centos/flask-app.tar.gz
    dest: /home/centos/
    remote_src: yes
  become: true
...