---
- include_role:
    name: update_cache

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
  when: ansible_distribution == "ec2-user"

- name: Install Python (Amazon|CentOs)
  yum:
    name: postgresql
    state: present
  when: ansible_distribution == "Amazon" or ansible_distribution == "CentOs"
...